/**
 * _shared/lib/gemini.ts
 * Inner G Complete Agency — Shared Gemini API Client
 *
 * ─────────────────────────────────────────────────────────
 * ⚠️  GUARDRAIL: DO NOT EDIT THIS FILE to add prompt logic.
 * System prompts and AI persona instructions belong in each
 * function's own `prompt-engineer.ts` file.
 * This file ONLY handles HTTP communication with the Gemini API.
 * ─────────────────────────────────────────────────────────
 *
 * Provides:
 *  - generateContent():  Sends a prompt to Gemini and returns the raw text
 *  - embedText():        Converts text to a vector embedding for RAG
 */

const GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta"

export const GEMINI_MODELS = {
    FLASH_LITE: "gemini-2.5-flash-lite",
    PRO: "gemini-2.5-pro",
    EMBED: "gemini-embedding-001",
} as const

export type GeminiModel = typeof GEMINI_MODELS[keyof typeof GEMINI_MODELS]

export interface GenerateContentOptions {
    model: GeminiModel
    systemPrompt?: string
    userMessage: string
    temperature?: number
    maxOutputTokens?: number
    responseSchema?: Record<string, unknown>
    history?: Array<{ role: string; parts: Array<{ text?: string; functionCall?: unknown; functionResponse?: unknown }> }>
    tools?: unknown[]
}

export interface GeminiResponse {
    text: string | null
    usage: { inputTokens: number; outputTokens: number }
    rawData: unknown
}

/**
 * Calls the Gemini generateContent API.
 * Returns the first text candidate and token usage.
 */
export async function generateContent(
    options: GenerateContentOptions,
    apiKey: string
): Promise<GeminiResponse> {
    const {
        model,
        systemPrompt,
        userMessage,
        temperature = 0.3,
        maxOutputTokens = 2048,
        responseSchema,
        history = [],
        tools,
    } = options

    const contents = [...history]
    const lastMessage = history[history.length - 1]
    
    // Only append userMessage if the history doesn't already end with it
    if (!lastMessage || lastMessage.role !== "user" || lastMessage.parts[0]?.text !== userMessage) {
        contents.push({ role: "user", parts: [{ text: userMessage }] })
    }

    const payload: Record<string, unknown> = {
        contents,
        generationConfig: {
            temperature,
            maxOutputTokens,
            ...(responseSchema ? {
                responseMimeType: "application/json",
                responseSchema,
            } : {})
        },
    }

    if (systemPrompt) {
        payload.system_instruction = { parts: [{ text: systemPrompt }] }
    }

    if (tools) {
        payload.tools = tools
    }

    const res = await fetch(
        `${GEMINI_API_BASE}/models/${model}:generateContent?key=${apiKey}`,
        {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
        }
    )

    if (!res.ok) {
        const errText = await res.text()
        throw new Error(`Gemini API Error (${res.status}): ${errText}`)
    }

    const data = await res.json()
    const usage = data.usageMetadata || {}

    return {
        text: data.candidates?.[0]?.content?.parts?.[0]?.text ?? null,
        usage: {
            inputTokens: usage.promptTokenCount || 0,
            outputTokens: usage.candidatesTokenCount || 0,
        },
        rawData: data,
    }
}

/**
 * Converts text to a 768-dimensional vector embedding using Gemini.
 * Used for RAG (Retrieval-Augmented Generation) searches.
 */
export async function embedText(text: string, apiKey: string): Promise<number[] | null> {
    console.log(`[GeminiEmbed] URL: ${GEMINI_API_BASE}/models/${GEMINI_MODELS.EMBED}:embedContent`)
    const res = await fetch(
        `${GEMINI_API_BASE}/models/${GEMINI_MODELS.EMBED}:embedContent?key=${encodeURIComponent(apiKey)}`,
        {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                model: `models/${GEMINI_MODELS.EMBED}`,
                content: { parts: [{ text }] },
                outputDimensionality: 768,
            }),
        }
    )

    if (!res.ok) {
        const error = await res.json()
        throw new Error(`Gemini Embedding Error: ${JSON.stringify(error)}`)
    }

    const data = await res.json()
    return data.embedding?.values ?? null
}
