/**
 * _shared/lib/response.ts
 * Inner G Complete Agency — Standardized Response Factory
 *
 * ─────────────────────────────────────────────────────────
 * ⚠️  GUARDRAIL: DO NOT EDIT THIS FILE to add feature logic.
 * All functions here must return a Response object only.
 * The payload shape must always match { data, error }.
 * ─────────────────────────────────────────────────────────
 *
 * Enforces a consistent API contract across all Edge Functions:
 *   Success: { data: <payload>, error: null }
 *   Error:   { data: null, error: { code: string, message: string } }
 */

import { corsHeaders } from "../cors.ts"

export interface ApiError {
    code: string
    message: string
    details?: unknown
}

/**
 * Returns a 200 OK response with the given data.
 */
export function okResponse(data: unknown, extraHeaders?: HeadersInit): Response {
    return new Response(
        JSON.stringify({ data, error: null }),
        {
            status: 200,
            headers: { ...corsHeaders, "Content-Type": "application/json", ...(extraHeaders ?? {}) }
        }
    )
}

/**
 * Returns a 400 Bad Request response for validation failures.
 */
export function validationErrorResponse(message: string, details?: unknown): Response {
    return errorResponse(400, "VALIDATION_ERROR", message, details)
}

/**
 * Returns a 401 Unauthorized response.
 */
export function unauthorizedResponse(message = "Authentication required."): Response {
    return errorResponse(401, "UNAUTHORIZED", message)
}

/**
 * Returns a 403 Forbidden response.
 */
export function forbiddenResponse(message = "Insufficient permissions."): Response {
    return errorResponse(403, "FORBIDDEN", message)
}

/**
 * Returns a 500 Internal Server Error response.
 */
export function serverErrorResponse(err: unknown): Response {
    return errorResponse(500, "SERVER_ERROR", String(err))
}

/**
 * Generic error response builder.
 */
function errorResponse(status: number, code: string, message: string, details?: unknown): Response {
    const body: { data: null; error: ApiError } = {
        data: null,
        error: { code, message, ...(details ? { details } : {}) }
    }
    return new Response(
        JSON.stringify(body),
        {
            status,
            headers: { ...corsHeaders, "Content-Type": "application/json" }
        }
    )
}

/**
 * Returns a response for OPTIONS (CORS preflight) requests.
 */
export function corsPreflightResponse(): Response {
    return new Response(null, { headers: corsHeaders })
}
