/**
 * _shared/lib/auth.ts
 * Inner G Complete Agency — Shared Authentication Library
 *
 * ─────────────────────────────────────────────────────────
 * ⚠️  GUARDRAIL: DO NOT EDIT THIS FILE to add feature logic.
 * This file ONLY handles JWT authentication and role verification.
 * To add a new role check, add a helper function below.
 * ─────────────────────────────────────────────────────────
 *
 * Provides:
 *  - createUserClient():    A user-scoped Supabase client (respects RLS)
 *  - createAdminClient():   A service-role Supabase client (bypasses RLS)
 *  - getAuthenticatedUser(): Verifies the JWT and returns the user
 *  - verifyRole():          Checks the user's role against an allow-list
 */

import { createClient, SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2"

export interface AuthUser {
    id: string
    email: string | undefined
    role: string
}

export interface AuthResult {
    user: AuthUser | null
    error: string | null
}

/**
 * Creates a Supabase client that operates on behalf of the authenticated user.
 * This is used for queries that must respect Row Level Security (RLS).
 */
export function createUserClient(authHeader: string): SupabaseClient {
    return createClient(
        Deno.env.get("SUPABASE_URL")!,
        Deno.env.get("SUPABASE_ANON_KEY")!,
        { global: { headers: { Authorization: authHeader } } }
    )
}

/**
 * Creates a Supabase client with the service role key.
 * This bypasses RLS and is reserved for system-level writes.
 * ⚠️ NEVER expose this client's results directly to the user.
 */
export function createAdminClient(): SupabaseClient {
    return createClient(
        Deno.env.get("SUPABASE_URL")!,
        Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    )
}

/**
 * Authenticates the user from the Authorization header.
 * Returns the user's ID, email, and DB role on success.
 */
export async function getAuthenticatedUser(
    authHeader: string | null,
    adminClient?: SupabaseClient
): Promise<AuthResult> {
    console.log(`[Auth] Checking auth header: ${authHeader ? 'Present' : 'Missing'}`)
    
    if (!authHeader) {
        return { user: null, error: "Missing Authorization header." }
    }

    // 1. Check for Service Role Key (System Access)
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")
    if (serviceRoleKey && authHeader.includes(serviceRoleKey)) {
        console.log(`[Auth] Path matched: Authenticated via Service Role Key`)
        return {
            user: {
                id: "00000000-0000-0000-0000-000000000000",
                email: "system@innergcomplete.com",
                role: "super_admin",
            },
            error: null,
        }
    }

    // 2. Validate token via getUser(jwt)
    // Strip "Bearer " if present to get raw JWT
    const jwt = authHeader.replace(/^Bearer\s+/i, "")
    const { data: { user }, error: authError } = await (adminClient ?? createAdminClient()).auth.getUser(jwt)

    if (authError || !user) {
        console.error(`[Auth] getUser failed: ${authError?.message || "No user found"}`)
        return { user: null, error: authError?.message || "Authentication failed." }
    }

    // Fetch the role from the public.users table
    const client = adminClient ?? createAdminClient()
    const { data: profile } = await client
        .from("users")
        .select("role")
        .eq("id", user.id)
        .single()

    console.log(`[Auth] Authenticated user: ${user.id} (role: ${profile?.role ?? "unknown"})`)

    return {
        user: {
            id: user.id,
            email: user.email,
            role: profile?.role ?? "unknown",
        },
        error: null,
    }
}

/**
 * Checks if a user has one of the allowed roles.
 * Returns true if the role is permitted, false otherwise.
 */
export function verifyRole(userRole: string, allowedRoles: string[]): boolean {
    return allowedRoles.includes(userRole)
}
