// IndexNow — instantly notify Bing (and Yandex, Seznam, etc. — they share one
// submission network) when a URL is created or changed, instead of waiting for
// a crawl. Ownership is proven by the key file served at KEY_LOCATION.
//
// The key is intentionally public (it's in the key file and every ping); it's
// an ownership token, not a secret. Keep INDEXNOW_KEY in sync with the file
// public/<key>.txt.
//
// This key was GENERATED BY BING WEBMASTER TOOLS for the verified site. Bing's
// IndexNow only authorizes the key it issued for the verified property — a
// self-generated key returns 403 UserForbiddedToAccessSite, which is exactly
// what happened with the previous key (be496c55…4c25).
const HOST = "agency.innergcomplete.com";
export const INDEXNOW_KEY = "e352d1c5dee74b9084f780187d522a3a";
const KEY_LOCATION = `https://${HOST}/${INDEXNOW_KEY}.txt`;
const ENDPOINT = "https://api.indexnow.org/indexnow";

// Absolutize a path or URL onto the production host.
export function toAbsoluteUrl(pathOrUrl: string): string {
  if (/^https?:\/\//i.test(pathOrUrl)) return pathOrUrl;
  return `https://${HOST}${pathOrUrl.startsWith("/") ? "" : "/"}${pathOrUrl}`;
}

/**
 * Build the request for a set of URLs.
 *
 * One URL goes as a GET with query parameters; several go as the POST urlList.
 * Bing classifies a site's submission mode by the SHAPE of the request, not by
 * how many URLs it carries — so posting a urlList of one made every ordinary
 * publish look like a batch submission, and Bing Webmaster Tools flagged the
 * site as batch mode even though the pings were already one page at a time.
 *
 * Separated from the network call so the shape can be tested, which is the
 * whole thing that was wrong.
 */
export function buildIndexNowRequest(urlList: string[]): {
  url: string;
  init: RequestInit;
  mode: "streaming" | "batch";
} {
  if (urlList.length === 1) {
    const q = new URLSearchParams({
      url: urlList[0],
      key: INDEXNOW_KEY,
      keyLocation: KEY_LOCATION,
    });
    return { url: `${ENDPOINT}?${q}`, init: { method: "GET" }, mode: "streaming" };
  }

  return {
    url: ENDPOINT,
    init: {
      method: "POST",
      headers: { "Content-Type": "application/json; charset=utf-8" },
      body: JSON.stringify({ host: HOST, key: INDEXNOW_KEY, keyLocation: KEY_LOCATION, urlList }),
    },
    mode: "batch",
  };
}

// Submit one or more URLs to IndexNow. Never throws — a failed ping must never
// break the publish flow that calls it. IndexNow accepts up to 10,000 URLs per
// request; callers submitting more should batch.
export async function pingIndexNow(urls: string[]): Promise<boolean> {
  const urlList = [...new Set(urls.filter(Boolean).map(toAbsoluteUrl))];
  if (urlList.length === 0) return false;

  // Paths are absolutized onto the PRODUCTION host regardless of where this
  // runs, so a publish performed from a dev server would tell Bing to crawl a
  // production URL that may not exist there yet — a self-inflicted 404 in the
  // index. Ping only from production; set INDEXNOW_FORCE=1 to override for a
  // deliberate backfill.
  if (process.env.NODE_ENV !== "production" && !process.env.INDEXNOW_FORCE) {
    console.log(`[IndexNow] skipped (non-production): ${urlList.join(", ")}`);
    return false;
  }

  try {
    const { url, init } = buildIndexNowRequest(urlList);
    const res = await fetch(url, init);
    // 200 = accepted, 202 = accepted (validation pending). Anything else is a
    // soft failure we just log.
    if (res.status !== 200 && res.status !== 202) {
      console.warn(`[IndexNow] ${res.status} for ${urlList.length} url(s)`);
      return false;
    }
    return true;
  } catch (e: any) {
    console.warn("[IndexNow] ping failed:", e?.message);
    return false;
  }
}
