import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://senkwhdxgtypcrtoggyf.supabase.co'
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY // will inject key via env

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

const ITERATION_ID = "11097194-c541-441b-bc63-4a37697afb94"

const responses = {
  "1-problem": "The grooming, beauty, and wellness industry (MedSpas, luxury salons, fitness franchises) suffers from two catastrophic, compounding financial leaks: (1) **The Blind Calendar** — high-paid specialist providers (aesthetic nurses, master barbers, personal trainers) operating with under-utilized schedules due to no-shows, poor predictive scheduling, and manual booking inefficiencies; and (2) **The Leaky Bucket** — enterprises spend heavily on client acquisition, but fail to convert consultations into bookings or secure rebookings before clients leave. Labor represents 35–45% of revenue; an empty chair for a senior clinician destroys margins instantly. No current platform solves both simultaneously with a unified, proprietary intelligence layer.",
  "1-success-measures": "Success for the initial ADI deployment is measured against the following primary KPIs:\n- **Rebooking Rate:** Target minimum 15% improvement over baseline within 90 days of pilot launch.\n- **Customer Lifetime Value (LTV):** Target measurable increase in per-client revenue via AI-driven personalization and retail upsell.\n- **Provider/Room Utilization Rate:** Reduce dead-calendar time by a measurable margin through predictive scheduling.\n- **Consultation-to-Conversion Rate:** Improve by a defined margin through cognitive intake and follow-up sequencing.\n- **Software TCO Reduction:** For multi-location franchises, demonstrate a net reduction in fragmented SaaS spend vs. the consolidated ADI license.",
  "1-budget": "[NEEDS INPUT]: Specific ADI engagement pricing (fixed fee, retainer, or revenue-share model) has not yet been defined. This must be established by the Inner G team before client-facing proposals are issued. Research establishes the market context: Multi-location enterprises currently spend $400–$1,500/month/location on fragmented tech stacks.",
  "1-roi": "The ROI case operates on two axes:\n- **Revenue Growth:** Increases in LTV, rebooking rates, and consultation-to-conversion rates directly expand top-line revenue per location.\n- **TCO Consolidation:** By replacing 3–4 fragmented SaaS platforms with the ADI intelligence layer, the enterprise reduces software overhead by an estimated $400–$1,500/month/location.\n- **Combined impact at scale:** A 50-location franchise realizing a 15% improvement in rebooking rates alongside a $500/month/location software consolidation represents a material six-figure annual swing.",
  "1-cognitive-need": "The core problem — predicting which client will no-show, understanding the nuanced intent behind a complex cosmetic inquiry, and personalizing omnichannel engagement at scale — requires pattern recognition across multiple data streams simultaneously. A static rule-based system cannot adapt to individual client behavior over time. Only a cognitive model can ingest appointment history, service preferences, product purchases, seasonal trends, and SKU-level data to make dynamic predictions that become more accurate with every client interaction.",
  "1-noncognitive-alt": "The primary non-AI alternatives have already been deployed industry-wide and are demonstrably failing:\n- **Mindbody / Zenoti / Phorest:** Static calendaring and CRM platforms that generate data but cannot act on it predictively. Mindbody's 700+ integration ecosystem fragments data, making unified analysis impossible.\n- **GoHighLevel / HubSpot Automation:** Rule-based \"if-then\" marketing flows that break when clients express non-linear, nuanced inquiries (e.g., \"I have rosacea—can I still get a chemical peel?\").",
  "1-hybrid-scope": "The ADI is deployed as a \"Headless Architecture\" — a sovereign intelligence layer sitting on top of the enterprise's existing non-AI infrastructure. The non-AI components remain:\n- **Payment Processing:** Stripe, Square, or existing gateway handles all transactions. ADI does not touch financial settlement.\n- **EMR / Clinical Records:** The existing Electronic Medical Record system (e.g., Aesthetix, PatientNow) continues to serve as the system of record for clinical data. ADI reads from it but does not replace it.\n- **Core Calendar UI:** The front-facing booking interface may remain the existing system; ADI operates via API to optimize what gets scheduled, not redesign the calendar UI.\n- **Human Clinical Judgment:** Licensed practitioners remain the final decision authority on all clinical and aesthetic procedures (HITL protocol).",
  "1-automation-alt": "Non-cognitive automation (rule-based bots, SMS autoresponders, standard email drip sequences) is possible for the most basic use cases. However, these tools are producing diminishing returns due to: (1) the \"empathy deficit\" — high-end wellness clients disengage from impersonal automation; (2) the inability to handle nuanced, multi-variable client conversations without hitting a dead end; and (3) the fundamental impossibility of predicting churn or optimizing scheduling without machine learning.",
  "1-cognitive-objectives": "The cognitive objectives for the ADI Phase 1 iteration are:\n1. Fine-tune a large language foundation model (Gemini) on grooming, beauty, and wellness domain-specific data to create an industry-calibrated conversational intelligence layer.\n2. Develop a predictive scheduling model that reduces provider under-utilization by identifying at-risk appointments and backfilling them.\n3. Deploy a personalization engine that generates individualized client engagement sequences.",
  "1-cognitive-outcomes": "The measurable cognitive outcomes targeted by the ADI are:\n- An AI engine that can engage a client via SMS/chat, understand their service intent without a human operator, and route them to the correct booking flow.\n- A predictive churn model that identifies \"at-risk\" clients and triggers an autonomous re-engagement sequence.\n- A recommendation engine that proposes relevant upsell services or retail products at the point of booking completion.\n- Long-term: A proprietary domain intelligence model that serves as a sovereign institutional asset.",
  "1-ai-vs-non-ai": "The ADI model uniquely provides:\n- **Continuous Learning:** It improves with every client interaction, booking event, and service completion.\n- **Cross-Signal Synthesis:** It simultaneously processes appointment data, purchase history, SMS engagement rates, seasonal patterns, and SKU-level data to produce a unified client intelligence score.\n- **Nuanced Language Understanding:** It can parse complex, unstructured client inquiries and respond with a personalized, clinically informed recommendation.",
  "1-ai-patterns": "The ADI Phase 1 iteration implements the following AI patterns:\n- **Generative AI / LLM (Fine-Tuned Foundation Model):** Conversational client engagement and intake, powered by a fine-tuned version of Google Gemini.\n- **Predictive Analytics / Classification:** No-show prediction and churn risk scoring.\n- **Recommendation System:** Personalized service and retail upsell recommendations at the point of booking.\n- **Natural Language Processing (NLP):** Intake form parsing, review sentiment analysis, and unstructured client feedback processing.",
  "1-schedule": "[NEEDS INPUT]: Are there any hard deadline constraints (e.g., a specific industry event, franchise renewal cycle, or board presentation date) that the enterprise requires the pilot to be delivered by?\nPhase 1 Business Audit: 2–4 weeks; Phase 2–4 MVP/Pilot Build & Single-Location Deployment: 8–12 weeks; Phase 5–6 Full Production / Franchise Rollout: 3–6 months",
  "1-tech-resources": "[NEEDS INPUT]: Specific enterprise tech stack is unknown until the Phase 1 Audit is completed with the first client.\nKnown resources: Google Gemini API (Vertex AI), GCP, Supabase, REST API connections, ETL tooling.",
  "1-skills": "- Large Language Model fine-tuning and prompt engineering\n- Machine learning pipeline development\n- Healthcare data engineering (HIPAA-compliant architecture)\n- REST API integration development\n- Domain expertise in grooming, beauty, and wellness industry operations\n- CPMAI-certified project management",
  "1-talent": "[NEEDS INPUT]: The specific team composition for the ADI build has not been formally defined. At minimum, the project requires: an AI/ML engineer, a backend API developer, a data engineer, a CPMAI-aligned project manager, and a domain consultant.",
  "1-other-constraints": "Data Readiness: The single biggest risk. If an enterprise client's data is fragmented, the data cleaning pipeline adds significant time. Client HIPAA Compliance Posture: If the enterprise client lacks a HIPAA-compliant infrastructure, Inner G must factor in additional time. Regulatory Gray Areas: The FDA SaMD (Software as a Medical Device) classification landscape for AI in aesthetics is evolving.",
  "1-performance-metrics": "False Positive (FP): The AI incorrectly flags a client as high-churn risk when they are not, triggering an unnecessary message. Cost: minor.\nFalse Negative (FN — CRITICAL): The AI fails to surface a contraindication (e.g., a client on Accutane is recommended a laser treatment). This is a catastrophic liability event. The model must default to human escalation whenever clinical uncertainty is detected.\nPerformance Targets will be defined during Phase 2.",
  "1-business-kpi": "- Rebooking Rate improvement (target: +15% from baseline within 90 days)\n- Client LTV growth (measured quarterly)\n- Provider/Room Utilization increase (measured weekly)\n- Consultation-to-Conversion Rate improvement\n- Software TCO reduction (vs. pre-ADI fragmented stack)",
  "1-tech-kpi": "[NEEDS INPUT — Partial Answer]:\n- Model response latency (target: <500ms for conversational responses)\n- Uptime/availability SLA (target: 99.9% for production)\n- Data pipeline throughput and sync frequency\nNote: Specific classification metrics cannot be set responsibly until Phase 2 data analysis is complete.",
  "1-trustworthy-ai": "The ADI project will adhere to the CPMAI Trustworthy AI framework, which mandates:\n1. Regulatory Compliance (HIPAA architecture)\n2. Transparency (Disclosed methodology to clients)\n3. Bias Management (Mandatory audit of training data via Monk Skin Tone Scale)\n4. Failure Mode Engineering (Conservative defaults, HITL required)\n5. Data Transparency (Data Source Disclosure document)\n6. Human-in-the-Loop (No autonomous clinical decisions)",
  "1-potential-harms": "Clinical Harm: AI-generated recommendation that overlooks a medical contraindication. Mitigation: HITL protocol.\nDemographic Bias Harm: Inferior recommendations for clients with darker skin tones. Mitigation: Training data diversity audit using Monk Skin Tone Scale.\nPrivacy/Data Breach Harm: PHI exposure. Mitigation: HIPAA-compliant infrastructure.\nFinancial Harm to Client: Incorrect churn or LTV predictions. Mitigation: Outputs labeled as \"recommendations\"; human sign-off required.",
  "1-failure-handling": "- Detection: Real-time monitoring tracking confidence scores; low scores escalate to a human operator.\n- Escalation Protocol: Any clinical query the model cannot confidently classify is immediately routed to a practitioner.\n- Drift Detection: Monthly audits of model performance against business KPIs.\n- Rollback Plan: The headless architecture design means the ADI can be bypassed without disrupting underlying operations if a failure is detected.",
  "1-risks": "1. Poor Data Readiness (Highest Probability): The enterprise client's data is fragmented or low-quality.\n2. Institutional Resistance: Staff resist adopting AI-generated recommendations.\n3. Regulatory Boundary Breach: Client attempts to use outputs for autonomous decisions (FDA SaMD scrutiny).\n4. Scope Creep: Expanding scope before model validation.\n5. Foundation Model API Dependency: Over-reliance on Gemini API.",
  "1-human-in-loop": "HITL is a non-negotiable design constraint:\n- All conversational AI outputs are reviewed by a coordinator before being sent (in Phase 1 pilot).\n- All clinical recommendations are reviewed and signed off by a licensed practitioner before communication.\n- Below a defined confidence score, the model flags for human review with a summary of its uncertainty.",
  "1-informational-bias": "- Training Data Audit: Dataset will be audited for demographic representation, specifically skin tone diversity via the Monk Skin Tone Scale.\n- Data Augmentation: Techniques matching under-represented groups.\n- Ongoing Audit: Post-deployment stratification by demographic segment.",
  "1-compliance": "- HIPAA: Signed BAAs, AES-256 encryption, PHI isolation.\n- CCPA / GDPR: For fitness & grooming data privacy.\n- FDA SaMD Gray Zone: The ADI is strictly Clinical Decision Support (CDS), not an autonomous diagnostic device.\n- State Medical Practice Laws: Supervised by licensed practitioners.",
  "1-data-source-transparency": "Inner G will provide a Data Source Disclosure Document identifying:\n- Categories of enterprise data ingested\n- Any third-party datasets used in fine-tuning\n- Anonymization methods used\n- The model's lineage (fine-tuned from Google Gemini)",
  "1-data-filter-transparency": "[NEEDS INPUT]: The specific data governance agreement template for client-facing transparency has not yet been drafted.\nAspects to cover:\n- Inclusion/exclusion criteria\n- Filtering for outliers/low-quality records\n- Rationale for data exclusions\n- Train/validation/test split method",
  "1-explainability": "- Operational recommendations: surface a plain-language rationale.\n- Clinical recommendations: the practitioner must be able to understand the model's reasoning.\n- Every high-stakes AI output will include a confidence score and supporting data signal.",
  "1-go-no-go-objectives": "GO. The business problem is clearly articulated — two compounding financial drains (Blind Calendar + Leaky Bucket) caused by the absence of a unified, predictive intelligence layer across the grooming, beauty, and wellness sector.",
  "1-go-no-go-customer": "[NEEDS INPUT — No-Go Hold]: This gate cannot be marked as GO until Inner G Complete has a confirmed enterprise client who has agreed in principle to implement the ADI pilot.",
  "1-go-no-go-roi": "GO (Conditional). Research supports a strong ROI case: measurable LTV and rebooking improvements combined with TCO consolidation of up to $900K annually for a 50-location franchise create a compelling financial argument. Specific ROI figures must be validated with real enterprise data.",
  "1-go-no-go-data-available": "[NEEDS INPUT — Conditional No-Go]: Data availability is the highest-risk variable in this project. Whether data is accessible and in a usable format is unknown until the Phase 1 Audit for each client.",
  "1-go-no-go-data-access": "[NEEDS INPUT — Conditional No-Go]: Access depends entirely on the enterprise client's willingness to grant Inner G data access under a signed BAA and Data Processing Agreement.",
  "1-go-no-go-data-quality": "[NEEDS INPUT — Conditional No-Go]: Given that fragmented data stacks are the norm in this industry, the working assumption is that data quality will require remediation. Marking as No-Go until Phase 2 data audit confirms sufficient baseline quality.",
  "1-go-no-go-tech-expertise": "GO (Conditional). Google Gemini and Vertex AI fine-tuning infrastructure are commercially available. HIPAA-compliant cloud infrastructure (GCP + Supabase) is accessible. Final GO depends on confirming team capacity.",
  "1-go-no-go-feasibility": "GO. The headless architecture approach has been validated as the industry best practice. The phased rollout model is the industry-standard deployment pattern. The CPMAI-governed timeline is realistic.",
  "1-go-no-go-sense": "GO. The technical approach is proven. Operationally, the HITL protocol mitigates clinical risk without requiring full regulatory approval. Financially, the TCO consolidation + LTV growth ROI model is credible."
};

async function seed() {
  const upserts = Object.keys(responses).map(key => ({
      iteration_id: ITERATION_ID,
      phase: 1,
      question_key: key,
      response_text: responses[key],
      ai_suggestion: null
  }));

  const { error } = await supabase
      .from("pm_responses")
      .upsert(upserts, { onConflict: 'iteration_id, question_key' });

  if (error) {
      console.error("Error upserting:", error);
  } else {
      console.log("Success! Upserted", upserts.length, "responses.");
  }
}

seed().catch(console.error);
