#!/usr/bin/env node
/**
 * Vendor the MCP Apps SDK browser bundle into lib/mcp/apps/vendor/.
 *
 * WHY VENDORED, AND WHY PINNED. The photo upload box (lib/mcp/apps) is a
 * self-contained HTML page served over MCP. The spec's default sandbox CSP
 * allows inline script only, so the SDK has to be inside the page, not loaded
 * from a CDN. The first version of the box hand-rolled the postMessage
 * protocol and never appeared in claude.ai; the SDK is what Claude is tested
 * against. Pinned so an SDK release cannot change the box without a commit.
 *
 * The bundle ends in one ESM `export{a as B,…}` statement, which an inline
 * classic <script> cannot contain. This rewrites that statement into
 * `window.McpExtApps = {B: a, …}` and escapes "</script" so the HTML parser
 * cannot end the inline script early.
 *
 *   node scripts/vendor_mcp_ext_apps.js            # uses VERSION below
 *
 * Licensing: the package is mid-transition from MIT to Apache-2.0. Its own
 * LICENSE file is copied beside the output rather than paraphrased here.
 */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const os = require("os");

const VERSION = "2.0.0";
const OUT = path.join(__dirname, "..", "lib", "mcp", "apps", "vendor", "ext-apps-bundle.ts");

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "ext-apps-"));
execSync(`curl -sL https://registry.npmjs.org/@modelcontextprotocol/ext-apps/-/ext-apps-${VERSION}.tgz | tar xz -C ${tmp}`);
let js = fs.readFileSync(path.join(tmp, "package", "dist", "src", "app-with-deps.js"), "utf8");

const m = /export\{([^}]*)\};?\s*$/.exec(js);
if (!m) throw new Error("bundle does not end in a single export statement — the rewrite needs revisiting");
const pairs = m[1].split(",").map((p) => {
  const [local, exported] = p.trim().split(/\s+as\s+/);
  return `${JSON.stringify(exported || local)}:${local}`;
});
js = js.slice(0, m.index) + `window.McpExtApps={${pairs.join(",")}};`;
if (/\bimport\s*[\s{*(]|import\.meta/.test(js.slice(0, 2000))) throw new Error("bundle has imports — it is not self-contained");
js = js.replace(/<\/script/gi, "<\\/script");
fs.copyFileSync(path.join(tmp, "package", "LICENSE"), path.join(path.dirname(OUT), "ext-apps-LICENSE"));

const header = `/* eslint-disable */
// GENERATED by scripts/vendor_mcp_ext_apps.js — do not edit by hand.
// @modelcontextprotocol/ext-apps ${VERSION}, dist/src/app-with-deps.js, with its final export
// rewritten to window.McpExtApps. License: see ext-apps-LICENSE in this directory.
export const EXT_APPS_VERSION = ${JSON.stringify(VERSION)};
export const EXT_APPS_BUNDLE = `;
fs.writeFileSync(OUT, header + JSON.stringify(js) + ";\n");
console.log(`wrote ${OUT} (${(js.length / 1024).toFixed(0)} KB, exports: ${pairs.length})`);
