import { MetricSlot } from "./types"

/**
 * METRIC_REGISTRY
 * 
 * The master list of all available "Slots" in the Inner G Complete ecosystem.
 * This registry allows the AI and the Slot System to dynamically compose
 * dashboards based on the user's role and project status.
 */
export const METRIC_REGISTRY: MetricSlot[] = [
    // --- MARKETING SLOTS (Client Facing) ---
    {
        id: "total_signups",
        label: "Total Signups",
        description: "Cumulative signups across all active GHL pipelines and funnels.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client', 'admin', 'super-admin'],
        iconName: "UserPlus"
    },
    {
        id: "app_installs",
        label: "Reader App Installs",
        description: "Total downloads and active installs of the client's proprietary reader app.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client', 'admin', 'super-admin'],
        iconName: "Download"
    },
    {
        id: "funnel_conversion",
        label: "Funnel Conversion",
        description: "Real-time conversion rate from lead generation to paid acquisition.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client', 'admin', 'super-admin'],
        iconName: "Zap"
    },
    {
        id: "social_reach",
        label: "Social Reach",
        description: "Aggregated reach across Instagram, Facebook, and LinkedIn architectures.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client', 'admin', 'super-admin'],
        iconName: "Instagram"
    },
    {
        id: "youtube_subscribers",
        label: "YT Subscribers",
        description: "Total subscriber count across connected YouTube channels.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client', 'admin', 'super-admin'],
        iconName: "Youtube"
    },
    {
        id: "youtube_views",
        label: "YouTube Views",
        description: "Total cumulative views from connected YouTube channel analytics.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client', 'admin', 'super-admin'],
        iconName: "Play"
    },

    // --- AGENCY SLOTS (Super Admin Only) ---
    {
        id: "active_architectures",
        label: "Active Architectures",
        description: "The total number of live client deployments currently managed by the agency.",
        category: 'agency',
        type: 'kpi',
        permissions: ['super-admin'],
        iconName: "Building2"
    },
    {
        id: "system_health",
        label: "Portfolio Health",
        description: "Real-time counter of unresolved critical/warning signals across the entire agency portfolio.",
        category: 'operations',
        type: 'kpi',
        permissions: ['super-admin'],
        iconName: "AlertTriangle"
    },
    {
        id: "agency_intelligence",
        label: "God Mode Insights",
        description: "High-level strategic patterns and private intelligence signals generated by the Agency AI.",
        category: 'agency',
        type: 'kpi',
        permissions: ['super-admin'],
        iconName: "Sparkles"
    },
    {
        id: "linkedin_followers",
        label: "LinkedIn Followers",
        description: "Total follower count for the connected LinkedIn organization page.",
        category: 'agency',
        type: 'kpi',
        permissions: ['admin', 'super-admin'],
        iconName: "Linkedin"
    },
    {
        id: "linkedin_impressions",
        label: "LinkedIn Reach",
        description: "Total impressions across all posts on the LinkedIn page.",
        category: 'agency',
        type: 'kpi',
        permissions: ['admin', 'super-admin'],
        iconName: "BarChart3"
    },
    {
        id: "linkedin_engagement",
        label: "LinkedIn Engagement",
        description: "Aggregated engagement rate across LinkedIn content architecture.",
        category: 'agency',
        type: 'kpi',
        permissions: ['admin', 'super-admin'],
        iconName: "Zap"
    },
    {
        id: "linkedin_clicks",
        label: "LinkedIn Clicks",
        description: "Total clicks on links and content within LinkedIn posts.",
        category: 'agency',
        type: 'kpi',
        permissions: ['admin', 'super-admin'],
        iconName: "Target"
    },
    {
        id: "linkedin_likes",
        label: "LinkedIn Likes",
        description: "Total likes aggregated across all posts in the LinkedIn content architecture.",
        category: 'agency',
        type: 'kpi',
        permissions: ['admin', 'super-admin'],
        iconName: "ThumbsUp"
    },
    {
        id: "linkedin_comments",
        label: "LinkedIn Comments",
        description: "Total comments aggregated across all posts in the LinkedIn content architecture.",
        category: 'agency',
        type: 'kpi',
        permissions: ['admin', 'super-admin'],
        iconName: "MessageSquare"
    },
    {
        id: "linkedin_shares",
        label: "LinkedIn Shares",
        description: "Total shares aggregated across all posts in the LinkedIn content architecture.",
        category: 'agency',
        type: 'kpi',
        permissions: ['admin', 'super-admin'],
        iconName: "Share2"
    },
    {
        id: "linkedin_post_views",
        label: "LinkedIn Post Views",
        description: "Cumulative view count aggregated across all individual LinkedIn posts.",
        category: 'agency',
        type: 'kpi',
        permissions: ['admin', 'super-admin'],
        iconName: "Eye"
    }
]

/**
 * Returns available slots based on the user's highest permission level.
 */
export function getAvailableSlots(userRole: 'client' | 'admin' | 'super-admin'): MetricSlot[] {
    return METRIC_REGISTRY.filter(slot => slot.permissions.includes(userRole))
}

/**
 * Returns a specific slot by its ID.
 */
export function getSlotById(id: string): MetricSlot | undefined {
    return METRIC_REGISTRY.find(slot => slot.id === id)
}
