import { MetricSlot } from "./types"

/**
 * METRIC_REGISTRY
 * 
 * The master list of all available "Slots" in the Inner G Complete ecosystem.
 * This registry allows the AI and the Slot System to dynamically compose
 * dashboards based on the user's role and project status.
 */
export const METRIC_REGISTRY: MetricSlot[] = [
    // --- MARKETING SLOTS (Client Facing) ---
    {
        id: "total_signups",
        label: "Total Signups",
        description: "Cumulative signups across all active GHL pipelines and funnels.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "UserPlus"
    },
    {
        id: "app_installs",
        label: "Reader App Installs",
        description: "Total downloads and active installs of the client's proprietary reader app.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Download"
    },
    {
        id: "funnel_conversion",
        label: "Funnel Conversion",
        description: "Real-time conversion rate from lead generation to paid acquisition.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Zap"
    },
    {
        id: "social_reach",
        label: "Omni-Channel Reach",
        description: "Aggregated reach across Instagram, Facebook, LinkedIn, and TikTok content architectures.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Instagram"
    },
    {
        id: "youtube_subscribers",
        label: "YT Subscribers",
        description: "Total subscriber count across connected YouTube channels.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Youtube"
    },
    {
        id: "youtube_views",
        label: "YouTube Views",
        description: "Total cumulative views from connected YouTube channel analytics.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Play"
    },
    {
        id: "youtube_video_count",
        label: "YouTube Videos",
        description: "Total number of videos published on the connected YouTube channels.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Video"
    },
    {
        id: "freelancer_registrations",
        label: "Freelancer Freedom",
        description: "Live tracking of registrations specifically for the School of Freelancer Freedom Pipeline.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "UserCheck"
    },

    // --- PIXEL SLOTS (Website Intelligence) ---
    {
        id: "pixel_total_pings",
        label: "Website Hits",
        description: "Total page views and interactions tracked by the Inner G Pixel.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Activity"
    },
    {
        id: "pixel_unique_visitors",
        label: "Unique Visitors",
        description: "Total unique browsers identified by the tracking pixel.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Users"
    },
    {
        id: "pixel_identified_count",
        label: "Identified Leads",
        description: "Total visitors successfully stitched to a social identity or email address.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "UserSearch"
    },

    // --- AGENCY SLOTS (Super Admin Only) ---
    {
        id: "active_architectures",
        label: "Active Architectures",
        description: "The total number of live client deployments currently managed by the agency.",
        category: 'agency',
        type: 'kpi',
        permissions: ['super-admin'],
        iconName: "Building2"
    },
    {
        id: "system_health",
        label: "Portfolio Health",
        description: "Real-time counter of unresolved critical/warning signals across the entire agency portfolio.",
        category: 'operations',
        type: 'kpi',
        permissions: ['super-admin'],
        iconName: "AlertTriangle"
    },
    {
        id: "agency_intelligence",
        label: "God Mode Insights",
        description: "High-level strategic patterns and private intelligence signals generated by the Agency AI.",
        category: 'agency',
        type: 'kpi',
        permissions: ['super-admin'],
        iconName: "Sparkles"
    },
    {
        id: "linkedin_followers",
        label: "LinkedIn Followers",
        description: "Total follower count for the connected LinkedIn organization page.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Linkedin"
    },
    {
        id: "linkedin_impressions",
        label: "LinkedIn Reach",
        description: "Total impressions across all posts on the LinkedIn page.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "BarChart3"
    },
    {
        id: "linkedin_engagement",
        label: "LinkedIn Engagement",
        description: "Aggregated engagement rate across LinkedIn content architecture.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Zap"
    },
    {
        id: "linkedin_clicks",
        label: "LinkedIn Clicks",
        description: "Total clicks on links and content within LinkedIn posts.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Target"
    },
    {
        id: "linkedin_likes",
        label: "LinkedIn Likes",
        description: "Total likes aggregated across all posts in the LinkedIn content architecture.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "ThumbsUp"
    },
    {
        id: "linkedin_comments",
        label: "LinkedIn Comments",
        description: "Total comments aggregated across all posts in the LinkedIn content architecture.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "MessageSquare"
    },
    {
        id: "linkedin_shares",
        label: "LinkedIn Shares",
        description: "Total shares aggregated across all posts in the LinkedIn content architecture.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Share2"
    },
    {
        id: "linkedin_post_views",
        label: "LinkedIn Post Views",
        description: "Cumulative view count aggregated across all individual LinkedIn posts.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Eye"
    },

    // --- TIKTOK ARCHITECTURE STUBS ---
    {
        id: "tiktok_followers",
        label: "TikTok Followers",
        description: "Total follower count across connected TikTok profiles.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Music"
    },
    {
        id: "tiktok_views",
        label: "TikTok Views",
        description: "Total video views across TikTok content architecture.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Play"
    },
    {
        id: "tiktok_likes",
        label: "TikTok Likes",
        description: "Aggregated heart count across all TikTok publications.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "ThumbsUp"
    },

    // --- FACEBOOK ARCHITECTURE STUBS ---
    {
        id: "facebook_page_likes",
        label: "Facebook Page Likes",
        description: "Total community size for connected Facebook Organization Pages.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Facebook"
    },
    {
        id: "facebook_reach",
        label: "Facebook Reach",
        description: "Total unique users who saw Facebook content in their feed.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "BarChart3"
    },
    {
        id: "facebook_engagement",
        label: "Facebook Engagement",
        description: "Total interactions (likes, shares, comments) on Facebook posts.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Zap"
    },

    // --- INSTAGRAM ARCHITECTURE (AGENCY LEVEL) ---
    {
        id: "instagram_followers",
        label: "Instagram Followers",
        description: "Total follower count for Agency-managed Instagram profiles.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Instagram"
    },
    {
        id: "instagram_reach",
        label: "Instagram Reach",
        description: "Total unique accounts reached across Instagram feed and stories.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "BarChart3"
    },
    {
        id: "instagram_impressions",
        label: "Instagram Impressions",
        description: "The total number of times your content was on-screen.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Eye"
    },
    {
        id: "instagram_engagement",
        label: "Instagram Engagement",
        description: "Aggregated interactions including likes, comments, and saves.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Zap"
    },
    {
        id: "instagram_profile_views",
        label: "IG Profile Views",
        description: "Total number of accounts that visited your Instagram profile.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "UserSquare2"
    },
    {
        id: "instagram_website_clicks",
        label: "IG Website Clicks",
        description: "Total taps on the link in your Instagram bio.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "ExternalLink"
    },
    {
        id: "instagram_post_views",
        label: "IG Video Views",
        description: "Cumulative view count aggregated across all Instagram Reels and Videos.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Eye"
    },
    {
        id: "instagram_interactions",
        label: "IG Interactions",
        description: "Total likes, comments, and saves aggregated across all Instagram media.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Zap"
    },
    {
        id: "instagram_post_success",
        label: "Automation Status",
        description: "Verifies the current AI write-access and publishing health for Instagram.",
        category: 'operations',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "CheckCircle2"
    },

    // --- THREADS ARCHITECTURE STUBS ---
    {
        id: "threads_followers",
        label: "Threads Followers",
        description: "Total follower count across connected Threads accounts.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "AtSign"
    },
    {
        id: "threads_likes",
        label: "Threads Likes",
        description: "Total likes aggregated across all Threads posts.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "ThumbsUp"
    },

    // --- X (TWITTER) ARCHITECTURE STUBS ---
    {
        id: "twitter_followers",
        label: "X (Twitter) Followers",
        description: "Total follower count across connected X/Twitter accounts.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Twitter"
    },
    {
        id: "twitter_impressions",
        label: "X (Twitter) Impressions",
        description: "Total number of times X/Twitter posts were seen.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "BarChart3"
    },
    {
        id: "twitter_engagement",
        label: "X (Twitter) Engagement",
        description: "Total interactions recorded across the X content archive.",
        category: 'agency',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Zap"
    },

    {
        id: "bookstore_inventory_value",
        label: "Inventory Asset Value",
        description: "Total real-time value of all physical and digital assets in the bookstore inventory.",
        category: 'finance',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "HardDrive"
    },
    {
        id: "active_readers",
        label: "Active Reader Base",
        description: "Total number of users currently engaged with the Reader App ecosystem.",
        category: 'marketing',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "BookOpen"
    },
    {
        id: "monthly_book_sales",
        label: "Monthly Sales Velocity",
        description: "Total book sales volume recorded in the current billing cycle.",
        category: 'finance',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "TrendingUp"
    },
    {
        id: "bookstore_total_orders",
        label: "Total Orders",
        description: "Cumulative order count synced from external store database.",
        category: 'finance',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "ShoppingBag"
    },
    {
        id: "bookstore_total_sales_value",
        label: "Total Order Value",
        description: "Gross revenue generated from all synced order records.",
        category: 'finance',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "DollarSign"
    },
    {
        id: "bookstore_avg_order_value",
        label: "Average Order Value",
        description: "Calculated average transaction value across all synced sales.",
        category: 'finance',
        type: 'kpi',
        permissions: ['client-admin', 'client-viewer', 'super-admin'],
        iconName: "Calculator"
    }
]

/**
 * Returns available slots based on the user's highest permission level.
 * Project-specific filtering is now handled dynamically by the database-backed SlotProvider.
 */
export function getAvailableSlots(
    userRole: 'client-admin' | 'client-viewer' | 'super-admin',
    _projectSlug?: string
): MetricSlot[] {
    return METRIC_REGISTRY.filter(slot => {
        // Check Permissions
        return slot.permissions.includes(userRole)
    })
}

/**
 * Returns a specific slot by its ID.
 */
export function getSlotById(id: string): MetricSlot | undefined {
    return METRIC_REGISTRY.find(slot => slot.id === id)
}
