import type { HeadMesh } from "./head-mesh";

/**
 * The block as a Wavefront OBJ, so it can be opened in Blender.
 *
 * WHY OBJ AND NOT glTF. glTF is the right format for the WEB — binary, compact,
 * what three.js loads natively. This file exists for the opposite direction:
 * getting the mesh OUT, into a modelling tool, by hand, once. OBJ is plain
 * text, every 3D application on earth imports it without a plugin, and it can
 * be read in a text editor when something looks wrong. A binary format would
 * add a writer to maintain and take away the ability to diff the thing.
 *
 * The round trip this is for: export the procedural block, open it in Blender,
 * add what a profile curve cannot express — an ear, a nose, a real jawline —
 * export .glb, load that back into the viewer. The point is to start from a
 * head rather than from a default cube, with the u-space alignment already
 * correct so the fade line still lands where the 2D overlay puts it.
 *
 * VERTEX COLOURS ARE WRITTEN, and are the one non-standard thing here. The
 * fade is per-vertex colour, and plain OBJ has no place for it — but most
 * importers, Blender included, accept six floats on a `v` line and read the
 * last three as colour. An importer that does not understand them ignores the
 * extra numbers and still gets the geometry, so nothing is lost by writing
 * them. Blender surfaces them as a colour attribute on the mesh.
 */

export interface ObjExportOptions {
  /** Appears in the file's header comment. */
  name?: string;
  /**
   * Multiplies every coordinate.
   *
   * Defaults to 10 because the mesh is built in head-heights — roughly one unit
   * tall — and Blender's default grid and clipping treat a one-unit object as
   * small. Ten lands it at a comfortable working size without anyone reaching
   * for the scale tool first thing.
   */
  scale?: number;
  /** Write per-vertex colours. On by default; see the note above. */
  includeColors?: boolean;
}

export function meshToObj(mesh: HeadMesh, opts: ObjExportOptions = {}): string {
  const scale = opts.scale ?? 10;
  const withColors = opts.includeColors ?? true;
  const name = opts.name ?? "shearquery-head";

  const out: string[] = [];
  out.push(`# ${name}`);
  out.push(`# Generated by ShearQuery — lib/hairstyle/export-obj.ts`);
  out.push(`# ${mesh.vertexCount} vertices, ${mesh.triangleCount} triangles`);
  out.push(`# Fade: ${mesh.plan.spec.height} / ${mesh.plan.spec.bottom} / top guard #${mesh.plan.spec.topGuard}`);
  out.push(`# Vertex colours encode hair length. Scale ${scale}x from head-heights.`);
  out.push(`o ${name}`);

  const f = (n: number) => (Math.abs(n) < 1e-6 ? "0" : n.toFixed(6));

  for (let i = 0; i < mesh.vertexCount; i++) {
    const x = mesh.positions[i * 3] * scale;
    const y = mesh.positions[i * 3 + 1] * scale;
    const z = mesh.positions[i * 3 + 2] * scale;
    if (withColors) {
      const r = mesh.colors[i * 3];
      const g = mesh.colors[i * 3 + 1];
      const b = mesh.colors[i * 3 + 2];
      out.push(`v ${f(x)} ${f(y)} ${f(z)} ${f(r)} ${f(g)} ${f(b)}`);
    } else {
      out.push(`v ${f(x)} ${f(y)} ${f(z)}`);
    }
  }

  for (let i = 0; i < mesh.vertexCount; i++) {
    out.push(
      `vn ${f(mesh.normals[i * 3])} ${f(mesh.normals[i * 3 + 1])} ${f(mesh.normals[i * 3 + 2])}`,
    );
  }

  // OBJ indices are 1-based, which is the single most common way to produce a
  // file that opens as a shredded mess.
  for (let i = 0; i < mesh.indices.length; i += 3) {
    const a = mesh.indices[i] + 1;
    const b = mesh.indices[i + 1] + 1;
    const c = mesh.indices[i + 2] + 1;
    out.push(`f ${a}//${a} ${b}//${b} ${c}//${c}`);
  }

  return out.join("\n") + "\n";
}

/**
 * A README to sit beside the export.
 *
 * Written because the round trip has two steps that are easy to get wrong and
 * whose failure is silent: importing at the wrong axis convention, and losing
 * the alignment that keeps the fade line where the 2D view puts it.
 */
export function exportReadme(scale: number): string {
  return [
    "ShearQuery head — Blender round trip",
    "===================================",
    "",
    "WHAT THIS IS",
    "  The procedural wig block, exported so you can start from a head instead",
    "  of a default cube. Vertex colours encode the fade: darker is longer hair.",
    "",
    "IMPORTING",
    "  File > Import > Wavefront (.obj). Take the defaults.",
    "",
    "  It arrives UPRIGHT with no settings changed. An earlier version of this",
    "  note told you to set Forward to -Z and Up to Y and warned that Blender",
    "  would otherwise lay the head on its side. That was written from memory",
    "  and it is wrong: -Z / Y is already what Blender 4.5's OBJ importer",
    "  defaults to, so the instruction was a no-op justified by a false reason.",
    "  Measured on 4.5.12: defaults and -Z/Y give an identical upright import,",
    "  and it is Forward -Y / Up Z — the setting that sounds like the Blender",
    "  convention — that lays it down.",
    "",
    "  The importer does this with an OBJECT rotation of 90 degrees on X, not",
    "  by rewriting the mesh. So do not Apply > Rotation: it bakes Z-up into the",
    "  vertices, and the .glb you export afterwards comes back into the web",
    "  viewer lying on its side.",
    "",
    `  The mesh is exported at ${scale}x. It is built in head-heights (~1 unit),`,
    "  which is uncomfortably small against Blender's default grid.",
    "",
    "WHAT TO CHANGE, AND WHAT NOT TO",
    "  Worth doing here: an ear, a nose, a real jawline — anything a profile",
    "  curve cannot express.",
    "",
    "  NOT worth doing here: the silhouette. Neck length, jaw width and crown",
    "  height are fifteen numbers in lib/hairstyle/mannequin.ts (PROFILE), and",
    "  editing them takes seconds and stays in version control. A shape sculpted",
    "  in Blender is a binary asset somebody has to maintain.",
    "",
    "GETTING IT BACK",
    "  Export as glTF Binary (.glb).",
    "",
    "  KEEP THE ORIGIN, ROTATION AND SCALE. The fade line is placed by height",
    "  along the head axis, so a mesh that has been moved, turned or rescaled",
    "  puts the line in the wrong place — and it will look plausible rather than",
    "  obviously broken, which is worse. Do not apply transforms.",
    "",
  ].join("\n");
}
