-- ============================================================
-- Migration 011: Create Invite Links Table
-- Inner G Complete Agency — Client Intelligence Portal
-- ============================================================
-- Powers the invite-only account creation flow.
-- Generated by: generate-invite-link Edge Function
-- Consumed by: the Supabase Auth invite redemption handler
-- ============================================================

CREATE TABLE public.invite_links (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token           TEXT NOT NULL UNIQUE,   -- sha256 hex — embedded in share URL
  invited_email   TEXT NOT NULL,
  intended_role   user_role NOT NULL,
  invited_by      UUID NOT NULL REFERENCES public.users(id),
  client_id       UUID REFERENCES public.clients(id),  -- NULL for developer invites
  expires_at      TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '7 days'),
  used_at         TIMESTAMPTZ,            -- Set when invite is redeemed
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_invite_links_token ON public.invite_links(token);
CREATE INDEX idx_invite_links_email ON public.invite_links(invited_email);
CREATE INDEX idx_invite_links_active ON public.invite_links(is_active, expires_at)
  WHERE is_active = TRUE;

-- Auto-deactivate expired invite links via a scheduled cleanup
-- (Alternatively handled in the generate-invite-link Edge Function on read)

COMMENT ON TABLE public.invite_links IS
  'One-time invite links for account creation. Generated by super_admin (for developers) or developers (for clients). 7-day expiry, single-use.';
COMMENT ON COLUMN public.invite_links.token IS
  'sha256 random token — embedded in invite URL as ?token=<value>. Single-use: used_at is set on redemption and is_active is set to FALSE.';
COMMENT ON COLUMN public.invite_links.client_id IS
  'Required for client_admin / client_viewer invites. NULL for developer invites (developers have portfolio-level access via developer_client_access).';
